# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'The version of release'
        required: true
        default: 'default'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get current date
        run: echo "verdefault=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Get current date2
        run: echo "verinput=${{ github.event.inputs.ver }}" >> $GITHUB_ENV
      - name: print inputs
        run: echo ${{ env.verinput }}
      - name: Print date
        run: echo ${{ env.verdefault }}
          
  
